# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-16 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lava_scheduler_app', '0018_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irc_handle', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name=b'IRC handle')),
                ('irc_server', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name=b'IRC server')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
