# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_scheduler_app', '0024_do_not_cascade_deletions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='job_status_trigger',
            field=models.CharField(choices=[(0, b'Submitted'), (1, b'Running'), (2, b'Complete'), (3, b'Incomplete'), (4, b'Canceled'), (5, b'Canceling')], default=2, max_length=30, verbose_name='Job status trigger'),
        ),
    ]
