# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 08:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('lava_scheduler_app', '0024_do_not_cascade_deletions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='job_status_trigger',
            field=models.CharField(choices=[(0, b'Submitted'), (1, b'Running'), (2, b'Complete'), (3, b'Incomplete'), (4, b'Canceled'), (5, b'Canceling')], default=2, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Job status trigger'),
        ),
    ]
