# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava_scheduler_app', '0037_notify_callback_separation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(editable=False, help_text='e.g. the device tree name(s)', max_length=200, primary_key=True, serialize=False, verbose_name='Alias for this device-type'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='name',
            field=models.CharField(editable=False, help_text='e.g. ARMv7', max_length=100, primary_key=True, serialize=False, verbose_name='Architecture version'),
        ),
        migrations.AlterField(
            model_name='bitwidth',
            name='width',
            field=models.PositiveSmallIntegerField(editable=False, help_text='integer: e.g. 32 or 64', primary_key=True, serialize=False, verbose_name='Processor bit width'),
        ),
        migrations.AlterField(
            model_name='core',
            name='name',
            field=models.CharField(editable=False, help_text='Name of a specific CPU core, e.g. Cortex-A9', max_length=100, primary_key=True, serialize=False, verbose_name='CPU core'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.SlugField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='processorfamily',
            name='name',
            field=models.CharField(editable=False, help_text='e.g. OMAP4, Exynos', max_length=100, primary_key=True, serialize=False, verbose_name='Processor Family'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='hostname',
            field=models.CharField(default=None, editable=False, max_length=200, primary_key=True, serialize=False, verbose_name='Hostname'),
        ),
    ]
