# Generated by Django 1.11.20 on 2019-03-06 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0038_set_default_device_health_maintenance")
    ]

    operations = [
        migrations.RemoveField(model_name="testjob", name="admin_notifications")
    ]
