# Generated by Django 1.10.7 on 2019-04-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lava_scheduler_app", "0039_remove_testjob_admin_notifications")]

    operations = [
        migrations.RemoveField(model_name="devicetype", name="aliases"),
        migrations.AddField(
            model_name="alias",
            name="device_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="lava_scheduler_app.DeviceType",
            ),
        ),
        migrations.AlterModelOptions(
            name="alias", options={"verbose_name_plural": "Aliases"}
        ),
    ]
