# Generated by Django 1.11.20 on 2019-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lava_scheduler_app", "0041_notification_charfield_to_textfield")]

    operations = [
        migrations.AddField(
            model_name="extendeduser",
            name="table_length",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=None,
                help_text="leave empty for system default",
                null=True,
                verbose_name="Table length",
            ),
        )
    ]
