# Copyright (C) 2020 Linaro Limited
#
# Author: Stevan Radakovic <stevan.radakovic@linaro.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 1.11.28 on 2020-04-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lava_scheduler_app", "0050_worker_version")]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="master_version_notified",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="Master version notified",
            ),
        )
    ]
