# Generated by Django 1.11.29 on 2020-12-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lava_scheduler_app", "0054_remoteartifactsauth")]

    operations = [
        migrations.AddField(
            model_name="notificationcallback",
            name="header",
            field=models.CharField(
                default="Authorization", max_length=64, verbose_name="Header name"
            ),
        )
    ]
