# Generated by Django 2.2.24 on 2021-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0055_notificationcallback_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="testjob",
            name="queue_timeout",
            field=models.BigIntegerField(
                blank=True, editable=False, null=True, verbose_name="Queue timeout"
            ),
        ),
    ]
