# Generated by Django 2.2.28 on 2022-12-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lava_scheduler_app", "0056_testjob_queue_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="documentation_link",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=300,
                null=True,
                verbose_name="Documentation link",
            ),
        ),
    ]
