# Generated by Django 2.2.28 on 2023-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("lava_scheduler_app", "0056_testjob_queue_timeout")]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "permissions": (("submit_to_device", "Can submit jobs to device"),)
            },
        ),
        migrations.AlterModelOptions(
            name="devicetype",
            options={
                "permissions": (
                    ("submit_to_devicetype", "Can submit jobs to device type"),
                )
            },
        ),
        migrations.RemoveField(model_name="worker", name="master_version_notified"),
    ]
