# Generated by Django 2.2.28 on 2023-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("lava_scheduler_app", "0057_auto_20230326_1353")]

    operations = [
        migrations.AddField(
            model_name="device",
            name="disable_health_check",
            field=models.BooleanField(
                default=False, verbose_name="Disable health check for this device"
            ),
        )
    ]
