# Generated by Django 3.2.19 on 2024-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0059_increase_remoteartifactsauth_token_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetype",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="Name"
            ),
        ),
    ]
