# Generated by Django 3.2.19 on 2024-05-29 12:20

from django.db import migrations, models

import lava_scheduler_app.validators


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0060_add_unique_constraint_for_all_get_or_create")
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="hostname",
            field=models.CharField(
                max_length=200,
                primary_key=True,
                serialize=False,
                validators=[lava_scheduler_app.validators.validate_non_slash],
                verbose_name="Hostname",
            ),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="name",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                validators=[lava_scheduler_app.validators.validate_non_slash],
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="hostname",
            field=models.CharField(
                default=None,
                max_length=200,
                primary_key=True,
                serialize=False,
                validators=[lava_scheduler_app.validators.validate_non_slash],
                verbose_name="Hostname",
            ),
        ),
    ]
