# Copyright (C) 2025 Collabora Limited
#
# Author: Igor Ponomarev <igor.ponomarev@collabora.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 3.2.19 on 2025-03-10 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0061_alter_devicetype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processorfamily",
            options={"verbose_name_plural": "Processor families"},
        ),
    ]
