# Generated by Django 3.2.19 on 2025-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0062_alter_processorfamily_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="testjob",
            index=models.Index(
                condition=models.Q(("health_check", False), ("state", 5)),
                fields=["actual_device", "-end_time"],
                name="device_finished_jobs_index",
            ),
        ),
    ]
