# Copyright 2026 NXP
#
# Author: Larry Shen <larry.shen@nxp.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 3.2.19 on 2026-04-27 16:03

from django.db import migrations, models

import lava_scheduler_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0063_testjob_device_finished_jobs_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetype",
            name="health_frequency",
            field=models.IntegerField(
                default=lava_scheduler_app.models.default_health_frequency,
                verbose_name="How often to run health checks",
            ),
        ),
    ]
