# Copyright (C) 2025 Collabora Limited
#
# Author: Igor Ponomarev <igor.ponomarev@collabora.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 4.2.23 on 2025-10-31 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0063_testjob_device_finished_jobs_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testjob",
            options={},
        ),
    ]
