# Copyright (C) 2026 Collabora Limited
#
# Author: Igor Ponomarev <igor.ponomarev@collabora.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 4.2.23 on 2026-03-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0063_testjob_device_finished_jobs_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSecret",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.SlugField(verbose_name="Secret's name")),
                ("value", models.BinaryField(verbose_name="Secret's value")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="lava_scheduler_app.testjob",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="jobsecret",
            constraint=models.UniqueConstraint(
                fields=("job", "name"), name="job_secret_name_uniq"
            ),
        ),
    ]
