# Copyright 2026 NXP
#
# Author: Larry Shen <larry.shen@nxp.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 3.2.19 on 2026-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lava_scheduler_app", "0066_blacklist_to_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="testjob",
            name="requested_device",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.CASCADE,
                related_name="+",
                to="lava_scheduler_app.device",
            ),
        ),
        migrations.AddField(
            model_name="testjob",
            name="requested_worker",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.CASCADE,
                related_name="+",
                to="lava_scheduler_app.worker",
            ),
        ),
    ]
