# Copyright (C) 2026 Collabora Limited
#
# Author: Igor Ponomarev <igor.ponomarev@collabora.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

# Generated by Django 4.2.28 on 2026-09-16 10:26
from __future__ import annotations

from itertools import islice

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Cast

CHUNK_SIZE = 20_000


def move_from_django_log_to_lava_log(apps, schema_editor):
    DjangoLogEntry = apps.get_model("admin", "LogEntry")
    ContentType = apps.get_model("contenttypes", "ContentType")
    LavaLogEntryDevice = apps.get_model("lava_scheduler_app", "LavaLogEntryDevice")
    LavaLogEntryWorker = apps.get_model("lava_scheduler_app", "LavaLogEntryWorker")
    LavaLogEntryTestJob = apps.get_model("lava_scheduler_app", "LavaLogEntryTestJob")
    Device = apps.get_model("lava_scheduler_app", "Device")

    device_to_worker_dict = dict(
        Device.objects.all().values_list("hostname", "worker_host_id")
    )

    def extra_create_keys(
        django_log_object, lava_model, lava_log_model
    ) -> dict[str, object]:
        if lava_log_model == LavaLogEntryDevice:
            return {
                "worker_id": device_to_worker_dict[django_log_object.object_id],
            }
        else:
            return {}

    def process_model(lava_model, lava_log_model, foreign_key_name):
        lava_model_ct = ContentType.objects.get_for_model(lava_model)
        django_log_objects = DjangoLogEntry.objects.filter(
            content_type=lava_model_ct,
            # The django logs might be referencing deleted Devices, Workers...
            object_id__in=(
                lava_model.objects.all()
                # object_id is a TextField but primary key might be an integer
                .annotate(_pk_as_text=Cast("pk", output_field=models.TextField()))
                .values("_pk_as_text")
            ),
        )

        django_log_objects_iterator = django_log_objects.iterator(CHUNK_SIZE)
        while django_log_chunk := tuple(
            islice(django_log_objects_iterator, CHUNK_SIZE)
        ):
            lava_log_model.objects.bulk_create(
                [
                    lava_log_model(
                        **{
                            foreign_key_name: django_log_object.object_id,
                            "user_id": django_log_object.user_id,
                            "change_message": django_log_object.change_message,
                            "action_time": django_log_object.action_time,
                            "action_flag": django_log_object.action_flag,
                            **extra_create_keys(
                                django_log_object, lava_model, lava_log_model
                            ),
                        }
                    )
                    for django_log_object in django_log_chunk
                ]
            )

        django_log_objects.delete()

    process_model(Device, LavaLogEntryDevice, "device_id")
    process_model(
        apps.get_model("lava_scheduler_app", "Worker"), LavaLogEntryWorker, "worker_id"
    )
    process_model(
        apps.get_model("lava_scheduler_app", "TestJob"),
        LavaLogEntryTestJob,
        "testjob_id",
    )


def move_from_lava_log_to_django_log(apps, schema_editor):
    DjangoLogEntry = apps.get_model("admin", "LogEntry")
    ContentType = apps.get_model("contenttypes", "ContentType")
    LavaLogEntryDevice = apps.get_model("lava_scheduler_app", "LavaLogEntryDevice")
    LavaLogEntryWorker = apps.get_model("lava_scheduler_app", "LavaLogEntryWorker")
    LavaLogEntryTestJob = apps.get_model("lava_scheduler_app", "LavaLogEntryTestJob")

    def process_log(lava_model, lava_log_model, foreign_key_name):
        lava_model_ct = ContentType.objects.get_for_model(lava_model)
        lava_log_objects = lava_log_model.objects.all().select_related(foreign_key_name)

        lava_log_objects_iterator = lava_log_objects.iterator(CHUNK_SIZE)

        while lava_log_chunk := tuple(islice(lava_log_objects_iterator, CHUNK_SIZE)):
            DjangoLogEntry.objects.bulk_create(
                [
                    DjangoLogEntry(
                        **{
                            "content_type_id": lava_model_ct.pk,
                            "object_id": getattr(lava_log_object, foreign_key_name).pk,
                            "object_repr": repr(
                                getattr(lava_log_object, foreign_key_name)
                            ),
                            "user_id": lava_log_object.user_id,
                            "change_message": lava_log_object.change_message,
                            "action_time": lava_log_object.action_time,
                            "action_flag": lava_log_object.action_flag,
                        }
                    )
                    for lava_log_object in lava_log_chunk
                ]
            )

        lava_log_objects.delete()

    process_log(
        apps.get_model("lava_scheduler_app", "Device"), LavaLogEntryDevice, "device"
    )
    process_log(
        apps.get_model("lava_scheduler_app", "Worker"), LavaLogEntryWorker, "worker"
    )
    process_log(
        apps.get_model("lava_scheduler_app", "TestJob"), LavaLogEntryTestJob, "testjob"
    )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("lava_scheduler_app", "0070_increase_tag_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LavaLogEntryWorker",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Addition"), (2, "Change"), (3, "Deletion")]
                    ),
                ),
                ("change_message", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lava_scheduler_app.worker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["worker", "-action_time"],
                        name="lava_schedu_worker__d6cb00_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LavaLogEntryTestJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Addition"), (2, "Change"), (3, "Deletion")]
                    ),
                ),
                ("change_message", models.TextField()),
                (
                    "testjob",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lava_scheduler_app.testjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["testjob", "-action_time"],
                        name="lava_schedu_testjob_b2a858_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LavaLogEntryDevice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Addition"), (2, "Change"), (3, "Deletion")]
                    ),
                ),
                ("change_message", models.TextField()),
                (
                    "device",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lava_scheduler_app.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lava_scheduler_app.worker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device", "-action_time"],
                        name="lava_schedu_device__dc63a5_idx",
                    ),
                    models.Index(
                        fields=["worker", "-action_time"],
                        name="lava_schedu_worker__94aec0_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            code=move_from_django_log_to_lava_log,
            reverse_code=move_from_lava_log_to_django_log,
        ),
    ]
