#!/bin/sh
echo starting processing $1
echo error >&2
for i in `seq 3`; do
sleep 2
echo $i
cat $1
echo
done
echo dashboard-put-result: http://disney.com >&3
for i in `seq 3 6`; do
sleep 2
echo $i
done
echo ending
