#!/usr/bin/env python

# Copyright (C) 2011 Linaro Limited
#
# Author: Paul Larson <paul.larson@linaro.org>
#
# This file is part of LAVA Dispatcher.
#
# LAVA Dispatcher is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# LAVA Dispatcher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <http://www.gnu.org/licenses>.

import optparse
import os
import sys

from lava_dispatcher import LavaTestJob


parser = optparse.OptionParser('%prog: lava-dispatch <json job file>')
parser.add_option(
    "--oob-fd", default=None, type=int, help="Write OOB data to this fd.")

(options, args) = parser.parse_args()

if len(args) != 1:
    parser.print_help()
    sys.exit(1)

if options.oob_fd:
    oob_file = os.fdopen(options.oob_fd, 'w')
else:
    oob_file = sys.stderr

with open(args[0]) as fd:
    jobdata = fd.read()

job = LavaTestJob(jobdata, oob_file)
#FIXME Return status
job.run()
