#!/usr/bin/env python

# Copyright (C) 2011 Linaro Limited
#
# Author: Paul Larson <paul.larson@linaro.org>
#
# This file is part of LAVA Dispatcher.
#
# LAVA Dispatcher is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# LAVA Dispatcher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <http://www.gnu.org/licenses>.

import sys

from lava_dispatcher import LavaTestJob


def usage(status):
    print >> sys.stderr, "Usage:\n    lava-dispatch <json job file>"
    sys.exit(status)

if len(sys.argv) != 2:
    usage(1)

if sys.argv[1] == "--help":
    usage(0)

with open(sys.argv[1]) as fd:
    jobdata = fd.read()

job = LavaTestJob(jobdata)
#FIXME Return status
job.run()
