#!/usr/bin/python
import json
from lava.actions import get_all_cmds
import sys
from lava.config import LAVA_SERVER_CFG
from lava.config import BOARD_CFG

def usage(status):
    print >> sys.stderr, "Usage:\n    lava-dispatch <json job file>"
    sys.exit(status)

if len(sys.argv) != 2:
    usage(1)

if sys.argv[1] == "--help":
    usage(0)

with open(sys.argv[1]) as fd:
    jobfile = json.loads(fd.read())

#load the two default configs.
LAVA_SERVER_CFG().load("cfg/lava-server.json")
BOARD_CFG().load("cfg/board-cfg.json")

lava_commands = get_all_cmds()

target = jobfile['target']
for cmd in jobfile['actions']:
    params = cmd.get('parameters', {})
    step = lava_commands[cmd['command']](target)
    step.run(**params)
