#!/usr/bin/env python

import sys
import lava.scheduler.daemon as schedulerd

if __name__ == "__main__":

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            schedulerd.start()
        elif 'stop' == sys.argv[1]:
            schedulerd.stop()
        elif 'restart' == sys.argv[1]:
            schedulerd.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "Usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)

