#!/usr/bin/python

import os

# The following line is mangled to point at the debian settings file
# at package build time.
os.environ['DJANGO_SETTINGS_MODULE'] = 'lava_server.settings.development'

from lava_scheduler_daemon.main import monitor_main

monitor_main()
