[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
junit_family = xunit2
# Ignore DeprecationWarning in pty module.
# lava-run is a single thread process.
# This warning only happens when pytest is running.
filterwarnings =
    default
    ignore:This process :DeprecationWarning:pty
