#!/bin/sh
retry=0
max_retry=4

while [ 1 ]
do
  yum -e 0 -y -q install "$@"
  return_value=$?
  [ "$return_value" = 0 ] && break
  [ "$retry" = "$max_retry" ] && exit $return_value

  echo "================================================="
  echo "($retry) Install failed... Retrying after some seconds"
  echo "================================================="
  sleep 60
  retry=$((retry+1))
done
