#!/bin/sh

set -eu

if ! which udevadm >/dev/null 2>&1; then
    exit 77
fi

test -f /etc/udev/rules.d/99-lava-dispatcher-host.rules


# lava-docker-worker.service must be installed, but not enabled by default
systemctl cat lava-docker-worker.service
! systemctl is-active lava-docker-worker.service
