#!/bin/sh

set -ex

cd ~

# test the installed package database
lava-server manage check
lava-server manage check --deploy
lava-server manage createsuperuser --username autopkgtest --noinput --email a@test.com
lava-server manage users add nobody --email b@test.com
lava-server manage users add staffer --email c@test.com --staff
lava-server manage workers add autopkgtest
lava-server manage workers add disabled --health MAINTENANCE
lava-server manage device-types add qemu
lava-server manage device-types list --all
lava-server manage devices add --device-type qemu --worker autopkgtest qemu01
lava-server manage devices list --all
lava-server manage devices update --health RETIRED qemu01
lava-server manage devices list --all

# test daemon handling
service lava-server-gunicorn restart
service lava-scheduler restart
service lava-worker restart
