#!/bin/sh

set -e

# test the installed package database
lava-server manage check
lava-server manage check --deploy
lava-server manage createsuperuser --username autopkgtest --noinput --email a@test.com
lava-server manage users add nobody --email b@test.com
lava-server manage users add staffer --email c@test.com --staff
lava-server manage workers add autopkgtest
lava-server manage device-types add qemu
lava-server manage device-types list --all
lava-server manage devices add --device-type qemu --worker autopkgtest qemu01
lava-server manage devices list --all
lava-server manage devices set --private --status RETIRED --health FAIL qemu01
lava-server manage devices list --all

# test daemon handling
service lava-server-gunicorn restart
service lava-server restart
service lava-master restart
service lava-slave restart

# scenario files are not packaged & need django support, test the local tree only.
./lava_server/manage.py test -v2 \
	lava_scheduler_app \
	lava_scheduler_daemon \
	linaro_django_xmlrpc.tests \
	lava_results_app

