#!/bin/sh
#
#This file is for Multi-Node test
#
#This command will produce in its standard output a representation of the
#device group that is participating in the multi-node test job.
#
#Usage: ``lava-group``
#
#The output format contains one line per device, and each line contains
#the hostname and the role that device is playing in the test, separated
#by a TAB character::
#
#	panda01	client
#	highbank01	loadbalancer
#	highbank02	backend
#	highbank03	backend

echo -e ${LAVA_GROUP}
