#NameVirtualHost 127.0.0.1:80
#<VirtualHost lava-server:80>
<VirtualHost *:80>
    ServerAdmin webmaster@localhost

    Alias /tmp/ /var/lib/lava/dispatcher/tmp/

    # Let apache2 handle these URIs
    ProxyPass /tmp !
    <IfModule mod_headers.c>
        Alias /static/ /usr/share/lava-server/static/
        ProxyPass /static/ !
    </IfModule>
    # Send web socket requests to lava-publisher
    ProxyPass /ws/ ws://127.0.0.1:8001/ws/
    ProxyPassReverse /ws/ ws://127.0.0.1:8001/ws/
    # Send request to Gunicorn
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
    ProxyPreserveHost On

    DocumentRoot /usr/share/lava-server/static/lava_server/

    <Directory /usr/share/lava-server/static>
        Options +FollowSymLinks -Indexes
        Require all granted
        <IfModule mod_headers.c>
            Header set Cache-Control "max-age=60, public"
            Header set X-Content-Type-Options nosniff
            Header set Access-Control-Allow-Origin "*"
            <FilesMatch "\.(css|eot|html|js|json|map|md|sh|svg|ttf|txt|xml|yaml)(\.gz)?$">
                Header set Vary Accept-Encoding
            </FilesMatch>
            <IfModule mod_rewrite.c>
                RewriteEngine On
                RewriteBase /static/
                RewriteRule \.gz$ - [E=no-gzip:1]
                RewriteCond %{HTTP:Accept-Encoding} gzip
                RewriteCond %{REQUEST_FILENAME}.gz -s
                RewriteRule ^(.*)\.(css|eot|html|js|json|map|md|sh|svg|ttf|txt|xml|yaml)$ $1.$2.gz [QSA]
                <FilesMatch "\.(css|eot|html|js|json|map|md|sh|svg|ttf|txt|xml|yaml)\.gz$">
                    Header set Content-Encoding gzip
                </FilesMatch>
            </IfModule>
        </IfModule>
        <FilesMatch "\.css(\.gz)?$">
            ForceType "text/css; charset=utf-8"
        </FilesMatch>
        <FilesMatch "\.html(\.gz)?$">
            ForceType "text/html; charset=utf-8"
        </FilesMatch>
        <FilesMatch "\.js(\.gz)?$">
            ForceType "text/javascript; charset=utf-8"
        </FilesMatch>
        <FilesMatch "\.md(\.gz)?$">
            ForceType "text/markdown; charset=utf-8"
        </FilesMatch>
        <FilesMatch "\.txt(\.gz)?$">
            ForceType "text/plain; charset=utf-8"
        </FilesMatch>
        <FilesMatch "\.(json|map)(\.gz)?$">
            ForceType application/json
        </FilesMatch>
        <FilesMatch "\.sh(\.gz)?$">
            ForceType application/x-sh
        </FilesMatch>
        <FilesMatch "\.svg(\.gz)?$">
            ForceType image/svg+xml
        </FilesMatch>
        <FilesMatch "\.eot(\.gz)?$">
            ForceType application/vnd.ms-fontobject
        </FilesMatch>
        <FilesMatch "\.ttf(\.gz)?$">
            ForceType font/ttf
        </FilesMatch>
        <FilesMatch "\.xml(\.gz)?$">
            ForceType application/xml
        </FilesMatch>
        <FilesMatch "\.yaml(\.gz)?$">
            ForceType application/yaml
        </FilesMatch>
    </Directory>

    <Directory /var/lib/lava/dispatcher/tmp>
        Options -Indexes
        Require all granted
        AllowOverride None
        <IfModule mod_php7.c>
            php_admin_flag engine Off
        </IfModule>
    </Directory>

    LogLevel info
    ErrorLog ${APACHE_LOG_DIR}/lava-server.log
    CustomLog ${APACHE_LOG_DIR}/lava-server.log combined
</VirtualHost>
