{% extends "base.jinja2" %}

{% set use_docker_com = true %}

{% set dependencies = [
    {"pkgs": "file python3-setuptools systemd-sysv tar"},
    {"pkgs": requires("debian", "buster", "lava-common") },
    {"pkgs": requires("debian", "buster", "lava-dispatcher") },
    {"pkgs": "android-sdk-libsparse-utils debootstrap dfu-util git libguestfs-tools nfs-kernel-server qemu-system-arm qemu-system-x86 rpcbind ser2net telnet tftpd-hpa u-boot-tools unzip xz-utils" },
    {"pkgs": "docker-ce-cli" },
] %}
