#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  lava-daemon.py
#
#  Copyright 2013 Linaro Limited
#  Author: Neil Williams <neil.williams@linaro.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

# Daemonise support for lava-slave, copied from
# lava-coordinator.

from lava.dispatcher.daemonise import daemonise

PIDFILE = '/var/run/lava-slave.pid'
LOGFILE = '/var/log/lava-dispatcher/lava-slave.log'


def main():
    # arguments are supplied by the init script and read inside the daemon
    # dispatcher-slave.py --hostname sylvester.codehelp --master tcp://localhost:5556 --log-socket tcp://localhost:5555 --level DEBUG
    return daemonise(PIDFILE, LOGFILE)

if __name__ == '__main__':
    main()
