#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-present Linaro Limited
#
# Author: Remi Duraffort <remi.duraffort@linaro.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

import os

from lava_dispatcher.worker import run

# ensure we will find lava-run when running uninstalled
bindir = os.path.abspath(os.path.dirname(__file__))
if bindir not in os.environ["PATH"].split(":"):
    os.environ["PATH"] = bindir + ":" + os.environ["PATH"]

run()
