.TH LAVA-OUTERR 1 "April 2026" "lava-dispatcher" "User Commands"
.SH NAME
lava-outerr \- helper for handling standard output and error streams in LAVA

.SH SYNOPSIS
.B lava-outerr

.SH DESCRIPTION
.B lava-outerr
is a helper program used by LAVA to process output streams during job
execution.

It is primarily intended for internal use by LAVA components and test
infrastructure rather than for direct interactive use by end users.

.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B Non-zero
An error occurred.

.SH SEE ALSO
.BR lava-dispatcher (1),
.BR lava-run (1)

.SH AUTHOR
.PP
This manual page was written by Christopher Obbard \c
.MT obbardc@debian.org
.ME \c
\ for the Debian GNU/Linux system.
