{% extends "base.jinja2" %}

{% set adduser_and_group = True %}

{% set dependencies = [
    {"pkgs": "apache2 gunicorn3 postgresql postgresql-client postgresql-common python3-setuptools" },
    {"pkgs": requires("debian", "buster", "lava-common") },
    {"pkgs": requires("debian", "buster", "lava-server") },
] %}

{% set pip_packages = ["sentry-sdk==0.16.3"] %}
