#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 Linaro Limited
#
# Author: Antonio Terceiro <antonio.terceiro@linaro.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

import sys

from lava_dispatcher_host.cmdline import main

if __name__ == "__main__":
    sys.exit(main(sys.argv))
