{% extends "base.jinja2" %}

{% set adduser_and_group = True %}

{% set dependencies = [
    {"pkgs": "adduser apache2 gunicorn3 iproute2 libjs-excanvas libjs-jquery libjs-jquery-flot libjs-jquery-typeahead libjs-sphinxdoc postgresql postgresql-client postgresql-common python3-setuptools systemd-sysv" },
    {"pkgs": requires("debian", "buster", "lava-common") },
    {"pkgs": requires("debian", "buster", "lava-server") },
    {"pkgs": "lava-coordinator" },
] %}

{% set pip_packages = ["sentry-sdk==0.11.2"] %}
