{% extends "base.jinja2" %}

{% set base_image = "debian:stretch-slim" %}
{% set adduser_and_group = True %}
{% set use_apt_lavasoftware_org = True %}

{% set dependencies = [
    {"pkgs": "adduser apache2 gunicorn3 iproute2 libjs-excanvas libjs-jquery libjs-jquery-flot libjs-jquery-typeahead postgresql postgresql-client postgresql-common python3-setuptools systemd-sysv" },
    {"pkgs": requires("debian", "stretch", "lava-common") },
    {"pkgs": requires("debian", "stretch-backports", "lava-common"), "from": "stretch-backports" },
    {"pkgs": requires("debian", "stretch", "lava-server") },
    {"pkgs": requires("debian", "stretch-backports", "lava-server"), "from": "stretch-backports" },
    {"pkgs": "libjs-sphinxdoc"},
] %}

{% set pip_packages = ["sentry-sdk==0.11.2"] %}
