{% extends "base.jinja2" %}

{% set dependencies = [
    {"pkgs": requires("debian", "trixie", "lava-common") },
    {"pkgs": requires("debian", "trixie", "lava-dispatcher") },
    {"pkgs": "android-sdk-libsparse-utils docker-cli dfu-util git libguestfs-tools ser2net telnet tftpd-hpa u-boot-tools unzip xz-utils zstd rpcbind nfs-common fastboot wget" },
    {"pkgs": "qemu-system-arm qemu-system-mips qemu-system-misc qemu-system-ppc qemu-system-sparc qemu-system-x86", "from": "trixie-backports" },
] %}

{% set pip_packages = ["avh-api==1.0.5"] %}
