{% extends "base.jinja2" %}

{% set use_docker_com = true %}

{% set dependencies = [
    {"pkgs": requires("debian", "buster", "lava-common") },
    {"pkgs": requires("debian", "buster", "lava-dispatcher") },
    {"pkgs": "android-sdk-libsparse-utils dfu-util git libguestfs-tools qemu-system-arm qemu-system-x86 ser2net telnet tftpd-hpa u-boot-tools unzip xz-utils zstd" },
    {"pkgs": "docker-ce-cli" },
] %}
