{% extends "base.jinja2" %}

{% set base_image = "debian:stretch-slim" %}

{% set use_docker_com = True %}

{% set dependencies = [
    {"pkgs": "file python3-setuptools systemd-sysv tar"},
    {"pkgs": requires("debian", "stretch", "lava-common") },
    {"pkgs": requires("debian", "stretch-backports", "lava-common"), "from": "stretch-backports" },
    {"pkgs": requires("debian", "stretch", "lava-dispatcher") },
    {"pkgs": requires("debian", "stretch-backports", "lava-dispatcher"), "from": "stretch-backports" },
    {"pkgs": "bridge-utils debootstrap dfu-util git libguestfs-tools nfs-kernel-server ntp openbsd-inetd qemu-system-arm qemu-system-x86 rpcbind rsync ser2net telnet tftpd-hpa u-boot-tools unzip xz-utils" },
    {"pkgs": "apache2 docker-ce-cli" }
] %}
