#!/bin/bash

PREFIX="<LAVA_TEST_RUNNER>:"
WORKFILE="/lava/lava-test-runner.conf"
RESULTSDIR="/lava/results"
BINDIR="/lava/bin"

hwcontext()
{
	mkdir -p ${RESULTSDIR}/hwcontext
	cpuinfo=${RESULTSDIR}/hwcontext/cpuinfo.txt
	meminfo=${RESULTSDIR}/hwcontext/meminfo.txt

	[ -f ${cpuinfo} ] || cat /proc/cpuinfo > ${cpuinfo}
	[ -f ${meminfo} ] || cat /proc/meminfo > ${meminfo}
}

swcontext()
{
	mkdir -p ${RESULTSDIR}/swcontext
	build=${RESULTSDIR}/swcontext/build.txt
	pkgs=${RESULTSDIR}/swcontext/pkgs.txt

	lava-os-build > ${build}

	# this has to print a list of installed packages that will look similar to
	# what android's package list does
	lava-installed-packages  > ${pkgs}
}

cleanup()
{
	# just adds a little handy debugging
	ls ${RESULTSDIR}
	echo "${PREFIX} calling sync"
	sync
	echo "${PREFIX} exiting"
}
trap cleanup INT TERM EXIT

export PATH=${BINDIR}:${PATH}
echo "${PREFIX} started"
mkdir -p ${RESULTSDIR}

# move the workfile to something timestamped and run that. This
# prevents us from running the same thing again after a reboot
TS=`date +%s`
mv ${WORKFILE} ${WORKFILE}-${TS}
WORKFILE=${WORKFILE}-${TS}

echo "${PREFIX} looking for installation work in ${WORKFILE}"
for line in $(cat ${WORKFILE}); do
	test=`basename $line`
        echo "${PREFIX} Check if network interface is up ..."
	if [ -f ${line}/install.sh ] ; then
            /bin/ping -W1 -c1 8.8.8.8
            if [ $? -ne 0 ] ; then
                echo "${PREFIX} WARNING: Network interface is down. Dependencies will not be installed."
		hwcontext
		swcontext
                exit 1
            fi
	    echo "${PREFIX} running ${test} installer ..."
	    /bin/sh ${line}/install.sh
	    if [ $? -ne 0 ] ; then
		echo "${PREFIX} ${test} installer failed, exiting"
		hwcontext
		swcontext
		exit 1
	    fi
	fi
done

echo "${PREFIX} save hardware/software context info..."
hwcontext
swcontext

echo "${PREFIX} looking for work in ${WORKFILE}"
for line in $(cat ${WORKFILE}); do
	test=`basename $line`
	echo "${PREFIX} running ${test} under lava-test-shell..."
	odir=${RESULTSDIR}/${test}-`date +%s`
	mkdir ${odir}
	mkdir ${odir}/attachments/
	cp ${line}/uuid ${odir}/analyzer_assigned_uuid
	cp ${line}/testdef.yaml ${odir}/
	cp ${line}/testdef_metadata ${odir}/
	cp ${line}/run.sh ${odir}/attachments/
	echo 'text/plain' > ${odir}/attachments/run.sh.mimetype
	if [ -f ${line}/install.sh ]; then
	    cp ${line}/install.sh ${odir}/attachments/
	    echo 'text/plain' > ${odir}/attachments/install.sh.mimetype
	fi
	# run.sh includes a "read -t <timeout>" which isn't supported by dash
	# so be sure to use bash
	lava-test-shell --output_dir ${odir} /bin/bash -e "${line}/run.sh"
	echo "${PREFIX} ${test} exited with: `cat ${odir}/return_code`"
done

