#!/bin/sh

# make sure we log to serial console
exec >/dev/console

PREFIX="<LAVA_TEST_RUNNER>:"
WORKFILE="/etc/lava-test-runner.conf"
RESULTSDIR="/lava/results"
BINDIR="/lava/bin"

hwcontext()
{
	cpuinfo=${RESULTSDIR}/cpuinfo.txt
	meminfo=${RESULTSDIR}/meminfo.txt

	[ -f ${cpuinfo} ] || cat /proc/cpuinfo > ${cpuinfo}
	[ -f ${meminfo} ] || cat /proc/meminfo > ${meminfo}
}

swcontext()
{
	build=${RESULTSDIR}/build.txt
	pkgs=${RESULTSDIR}/pkgs.txt

	[ -f ${build} ] || cat /etc/lsb-release | grep DESCRIPTION | cut -d\" -f2 > ${build}
	# this does a query of installed packaged that will look similar to
	# what android's package list does
	[ -f ${pkgs} ]  || dpkg-query -W -f '${status} ${package} : ${version}\n' | sed -n 's/^install ok installed/package:/p'  > ${pkgs}
}

export PATH=${BINDIR}:${PATH}
echo "${PREFIX} started"
[ -d ${RESULTSDIR} ] || mkdir -p ${RESULTSDIR}

echo "${PREFIX} looking for installation work in ${WORKFILE}"
while read line ; do
	test=`basename $line`
	if [ -f ${line}/install.sh ] ; then
		echo "${PREFIX} running ${test} installer ..."
		/bin/sh ${line}/install.sh
		if [ $? -ne 0 ] ; then
			echo "${PREFIX} ${test} installer failed, exiting"
			hwcontext
			swcontext
			exit 1
		fi
	fi
done < ${WORKFILE}

echo "${PREFIX} save hardware/software context info..."
hwcontext
swcontext

echo "${PREFIX} looking for work in ${WORKFILE}"
while read line ; do
	test=`basename $line`
	echo "${PREFIX} running ${test} under lava-test-shell..."
	odir=${RESULTSDIR}/${test}-`date +%s`
	mkdir ${odir}
	cp ${line}/* ${odir}/
	lava-test-shell --output_dir ${odir} /bin/sh -e "${line}/run.sh"
	echo "${PREFIX} ${test} exited with: `cat ${odir}/return_code`"
done < ${WORKFILE}
echo "${PREFIX} exiting"

