#!/bin/bash

PREFIX="<LAVA_TEST_RUNNER>:"
WORKFILE="/lava/lava-test-runner.conf"
RESULTSDIR="/lava/results"
BINDIR="/lava/bin"

hwcontext()
{
	mkdir -p ${RESULTSDIR}/hwcontext
	cpuinfo=${RESULTSDIR}/hwcontext/cpuinfo.txt
	meminfo=${RESULTSDIR}/hwcontext/meminfo.txt

	[ -f ${cpuinfo} ] || cat /proc/cpuinfo > ${cpuinfo}
	[ -f ${meminfo} ] || cat /proc/meminfo > ${meminfo}
}

swcontext()
{
	mkdir -p ${RESULTSDIR}/swcontext
	build=${RESULTSDIR}/swcontext/build.txt
	pkgs=${RESULTSDIR}/swcontext/pkgs.txt

	[ -f ${build} ] || cat /etc/lsb-release | grep DESCRIPTION | cut -d\" -f2 > ${build}
	# this does a query of installed packaged that will look similar to
	# what android's package list does
	[ -f ${pkgs} ]  || dpkg-query -W -f '${status} ${package} : ${version}\n' | sed -n 's/^install ok installed/package:/p'  > ${pkgs}
}


cleanup()
{
	# just adds a little handy debugging
	ls ${RESULTSDIR}
	echo "${PREFIX} calling sync"
	sync
	echo "${PREFIX} exiting"
}
trap cleanup INT TERM EXIT

export PATH=${BINDIR}:${PATH}
echo "${PREFIX} started"
mkdir -p ${RESULTSDIR}

# move the workfile to something timestamped and run that. This
# prevents us from running the same thing again after a reboot
TS=`date +%s`
mv ${WORKFILE} ${WORKFILE}-${TS}
WORKFILE=${WORKFILE}-${TS}

echo "${PREFIX} looking for installation work in ${WORKFILE}"
while read line ; do
	test=`basename $line`
	if [ -f ${line}/install.sh ] ; then
		echo "${PREFIX} running ${test} installer ..."
		/bin/sh ${line}/install.sh
		if [ $? -ne 0 ] ; then
			echo "${PREFIX} ${test} installer failed, exiting"
			hwcontext
			swcontext
			exit 1
		fi
	fi
done < ${WORKFILE}

echo "${PREFIX} save hardware/software context info..."
hwcontext
swcontext

echo "${PREFIX} looking for work in ${WORKFILE}"
for line in $(cat ${WORKFILE}); do
	test=`basename $line`
	echo "${PREFIX} running ${test} under lava-test-shell..."
	odir=${RESULTSDIR}/${test}-`date +%s`
	mkdir ${odir}
	mkdir ${odir}/attachments/
	cp ${line}/uuid ${odir}/analyzer_assigned_uuid
	cp ${line}/testdef.yaml ${odir}/
	cp ${line}/run.sh ${odir}/attachments/
	echo 'text/plain' > ${odir}/attachments/run.sh.mimetype
	if [ -f ${line}/install.sh ]; then
	    cp ${line}/install.sh ${odir}/attachments/
	    echo 'text/plain' > ${odir}/attachments/install.sh.mimetype
	fi
	# run.sh includes a "read -t <timeout>" which isn't supported by dash
	# so be sure to use bash
	lava-test-shell --output_dir ${odir} /bin/bash -e "${line}/run.sh"
	echo "${PREFIX} ${test} exited with: `cat ${odir}/return_code`"
done

