#!/system/bin/mksh

LCK=${LCK-"/lava-test-runner.lck"}

#make sure we are only run once
if [ ! -f ${LCK} ] ; then
	( flock -n 9 || exit 1 ; true ) 9>${LCK}
else
	exit 0
fi

# make sure we log to serial console
exec >/dev/console

PREFIX="<LAVA_TEST_RUNNER>:"
WORKFILE="/data/lava/lava-test-runner.conf"
RESULTSDIR="/data/lava/results"
BINDIR="/data/lava/bin"

hwcontext()
{
        mkdir -p ${RESULTSDIR}/hwcontext
	cpuinfo=${RESULTSDIR}/hwcontext/cpuinfo.txt
	meminfo=${RESULTSDIR}/hwcontext/meminfo.txt

	[ -f ${cpuinfo} ] || cat /proc/cpuinfo > ${cpuinfo}
	[ -f ${meminfo} ] || cat /proc/meminfo > ${meminfo}
}

swcontext()
{
        mkdir -p ${RESULTSDIR}/swcontext
	build=${RESULTSDIR}/swcontext/build.txt
	pkgs=${RESULTSDIR}/swcontext/pkgs.txt

	[ -f ${build} ] || getprop ro.build.display.id > ${build}
	[ -f ${pkgs} ] || pm list packages -v > ${pkgs}
}

cleanup()
{
	# just adds a little handy debugging
	ls ${RESULTSDIR}
	echo "${PREFIX} calling sync"
	sync
	echo "${PREFIX} exiting"
}

# in background, since we don't have this working as a proper android service
{
	trap cleanup INT TERM EXIT

	export PATH=${BINDIR}:${PATH}
	echo "${PREFIX} started"
	mkdir -p ${RESULTSDIR}

	echo "${PREFIX} disabling suspend and waiting for home screen ..."
	disablesuspend.sh

	# move the workfile to something timestamped and run that. This
	# prevents us from running the same thing again after a reboot
	TS=`date +%s`
	mv ${WORKFILE} ${WORKFILE}-${TS}
	WORKFILE=${WORKFILE}-${TS}

	echo "${PREFIX} looking for installation work in ${WORKFILE}"
	while read line ; do
		test=`basename $line`
		if [ -f ${line}/install.sh ] ; then
			testdir=${line%/} # trim off trailing slash iff it exists
			test=${testdir/*\//}
			echo "${PREFIX} running ${test} installer ..."
			/system/bin/sh ${line}/install.sh
			if [ $? -ne 0 ] ; then
				echo "${PREFIX} ${test} installer failed, exiting"
				hwcontext
				swcontext
				exit 1
			fi
		fi
	done < ${WORKFILE}

	echo "${PREFIX} save hardware/software context info..."
	hwcontext
	swcontext

	echo "${PREFIX} looking for work in ${WORKFILE}"
	while read line ; do
		# we don't have "basename" on android, but this is does the
		# equivalent under mksh
		test=${testdir/*\//}
		echo "${PREFIX} running ${test} under lava-test-shell..."
		odir=${RESULTSDIR}/${test}-`date +%s`
		mkdir ${odir}
		mkdir ${odir}/attachments/
		cp ${line}/testdef.yaml ${odir}/
		cp ${line}/run.sh ${odir}/attachments/
		[ -f ${line}/install.sh ] && cp ${line}/install.sh ${odir}/attachments/
		lava-test-shell --output_dir ${odir} /system/bin/sh -e "${line}/run.sh"
		echo "${PREFIX} ${test} exited with: `cat ${odir}/return_code`"
	done < ${WORKFILE}
} &

